service: serverless-lambda
useDotenv: true

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: /
          method: get
          cors: true
